#!/bin/bash
#

NAME=mcluster-mysqld

. /opt/letv/mcluster/service-environment
for sclname in $MCLUSTER_MYSQLD_SCLS_ENABLED ; do
    . /opt/letv/mcluster/enable
    export X_SCLS="$X_SCLS $sclname"
done

# we want start daemon only inside "scl enable" invocation
if ! scl_enabled mcluster ; then
    echo "Collection mcluster has to be listed in /opt/letv/mcluster/service-environment"
    exit 1
fi

function rand_pass()
{
	head -c6 /dev/urandom | base64
}

function sst_user()
{
	local rootpwd="$1"
	local sstpwd="$2"

	if [ x"$sstpwd" == x ]; then
		echo "sst user password is empty"
		return 1
	fi

	echo The sstuser password is "$sstpwd"

#CREATE USER 'sstuser'@'localhost' IDENTIFIED BY 's3cret';
	mysql -uroot -p"$rootpwd" <<EOF
CREATE USER 'sstuser'@'localhost' IDENTIFIED BY '$sstpwd';
GRANT RELOAD, LOCK TABLES, REPLICATION CLIENT ON *.* TO 'sstuser'@'localhost';
FLUSH PRIVILEGES;
EOF

}


SSTPASS="`rand_pass`"

if ! service $NAME status >/dev/null; then
        echo 
        echo "Danger!! This will setup a new cluster."
        echo "Press Ctrl-C to cancel"

        echo

        echo -n "The process will start in 10 secs: "
        echo -e -n "----------\r"

        echo -n "The process will start in 10 secs: "
        for i in `seq 1 10`; do
                echo -n .
                sleep 1
        done

        echo " DONE"


        #mysql_install_db

	echo Setting up __SCL_ROOT__/etc/my.cnf
	sed -i "s|^wsrep_sst_auth=.*$|wsrep_sst_auth='sstuser:$SSTPASS'|" __SCL_ROOT__/etc/my.cnf

	echo "Starting new mysql cluster"
	if service $NAME start --wsrep-cluster-address="gcomm://"; then
		echo -n "Waiting the new mcluster to be ready.."
		while :; do
			sleep 1
			if service $NAME status >/dev/null 2>&1; then
				mysqladmin -uroot password 'Mcluster' >/dev/null 2>&1 && break 
			fi
			echo -n .
		done

		echo " DONE"

		sst_user Mcluster "$SSTPASS"
		
		echo "New mcluster started, you can copy the __SCL_ROOT__/etc/my.cnf to other nodes"
	else
		echo "Error! $NAME daemon failed to start, please check manually"
	fi
else
	echo "This will setup a new cluster, if this is what want to do, please stop the mysql first then try this again."
fi
